version: "3.9"

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb+srv://admin:GoConcert_admin@goconcert.zbbv9s6.mongodb.net/goconcert_db?retryWrites=true&w=majority
      TICKETMASTER_API_KEY: e6GnItapDxy0zQVPEKV0Obfr2gEtWuFm

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_PROXY_TARGET: http://backend:8000
    depends_on:
      - backend
